version: "3"

volumes:
  data:
  export:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
networks:
  sonar_network:

services:
  postgres-db:
    image: docker.io/postgres:17-alpine
    container_name: postgres-sql-eval
    hostname: postgres-db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data 
      - export:/export
    networks:
      - sonar_network

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    hostname: sonarqube
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9092:9092"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-db:5432/postgres
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    networks:
      - sonar_network
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
